name: Run npm test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test on Node.js v14.15.1 
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.1'
    - run: npm i
    - run: npm test
